In [2]:
import torch
O = 5
A = 2
D = torch.empty((10,O,A,1,O,1)) #<D_size,s,a,r,s',d> 
D.shape

torch.Size([10, 5, 2, 1, 5, 1])

In [ ]:
!pip install gymnasium
!pip install mujoco
!pip install imageio
import gymnasium as gym

In [ ]:
import gymnasium as gym
import torch
import numpy as np
env = gym.make('Hopper-v5',exclude_current_positions_from_observation=True)
obs,info = env.reset()
env.observation_space.shape
print(obs)
obs1 = np.concat((obs[:5],obs[7:]),axis=0)
print(obs1)
obs2 = np.concat((obs[:5],obs[7:]),axis=-1)
print(obs2)
next_obs = torch.tensor(obs,dtype=torch.float32,device='device')
next_obs

[ 1.24588440e+00  3.05326236e-03  2.60189127e-03 -2.02740776e-03
 -2.68946182e-03  1.92334490e-03 -4.36620385e-03  4.83665787e-03
 -3.16891182e-05  3.90629830e-03 -5.50844887e-04]
[ 1.24588440e+00  3.05326236e-03  2.60189127e-03 -2.02740776e-03
 -2.68946182e-03  4.83665787e-03 -3.16891182e-05  3.90629830e-03
 -5.50844887e-04]
[ 1.24588440e+00  3.05326236e-03  2.60189127e-03 -2.02740776e-03
 -2.68946182e-03  4.83665787e-03 -3.16891182e-05  3.90629830e-03
 -5.50844887e-04]


AssertionError: Torch not compiled with CUDA enabled

In [1]:
[0 for i in range(0,7)]

[0, 0, 0, 0, 0, 0, 0]

In [4]:
padding_mask

tensor([False,  True, False, False, False])

In [ ]:
import torch
padding_mask = torch.zeros((B,L,)).bool()
padding_mask[:,1] = True
padding_mask
p2 = torch.repeat_interleave(padding_mask,5).reshape(2,5,5).transpose(-2,-1)
p2 = torch.repeat_interleave(padding_mask,5).reshape(2,5,5).transpose(-2,-1)
p2


tensor([[[False,  True, False, False, False],
         [False,  True, False, False, False],
         [False,  True, False, False, False],
         [False,  True, False, False, False],
         [False,  True, False, False, False]],

        [[False,  True, False, False, False],
         [False,  True, False, False, False],
         [False,  True, False, False, False],
         [False,  True, False, False, False],
         [False,  True, False, False, False]]])

In [1]:
import numpy as np
act_features = 3
actions = np.array([1/act_features for i in range(act_features)])

In [2]:
actions

array([0.33333333, 0.33333333, 0.33333333])